version: "3.8"
services:
  proxy:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:${VERSION}
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:81
      - 80:80
      - 443:443
    volumes:
      - ./data/data:/data
      - ./data/letsencrypt:/etc/letsencrypt
