#!/bin/bash
 
TITLE="${OMV_NOTIFICATION_SUBJECT}"
MESSAGE=$(head "${OMV_NOTIFICATION_MESSAGE_FILE}")
PRIORITY=0
URL="https://<URL>/message?token=<TOKEN>"
 
curl -s -S --data '{"message": "'"${MESSAGE}"'", "title": "'"${TITLE}"'", "priority":'"${PRIORITY}"', "extras": {"client::display": {"contentType": "text/markdown"}}}' -H 'Content-Type: application/json' "$URL"