services:
  grafana:
    container_name: grafana
    image: grafana/grafana:${VERSION}
    restart: unless-stopped
    user: 0:0
    ports:
      - ${WEB_PORT}:3000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/data:/var/lib/grafana
