services:
  gotify:
    container_name: gotify
    image: gotify/server:${VERSION}
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:80
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/data:/app/data
