services:
  db:
    container_name: wikijs-postgress
    image: postgres:${VERSION_DB}
    restart: unless-stopped
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/db-data:/var/lib/postgresql/data
  wiki:
    container_name: wikijs
    image: ghcr.io/requarks/wiki:${VERSION}
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ${PASSWORD_DB}
      DB_NAME: wiki
    ports:
      - ${WEB_PORT}:3000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
