services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:${VERSION}
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:80
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/data:/data/
