version: "3.8"
services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:${VERSION}
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./data/data:/data/
