services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:${VERSION}
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:80/tcp
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/workdir:/opt/adguardhome/work
      - ./data/confdir:/opt/adguardhome/conf
