version: "3.3"
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:${VERSION}
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:3001
    volumes:
      - ./data/data:/app/data
