services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:${VERSION}
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:3001
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/data:/app/data
