services:
  file-browser:
    container_name: file-browser
    image: filebrowser/filebrowser:${VERSION}
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:80
    user: 0:0
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /:/srv
      - ./data/database.db:/database.db
