version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /path/to/stacks:/path/to/stacks
    environment:
      - DOCKGE_STACKS_DIR=/path/to/stacks
