services:
  influxdb:
    container_name: influxdb
    image: influxdb:${VERSION}
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:8086
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/data:/var/lib/influxdb2
