services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:${VERSION}
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:1883
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/config:/mosquitto/config
      - ./data/log:/mosquitto/log
      - ./data/data:/mosquitto/data
